version: "3"
services:
  node-app:
    container_name: express-node-app-container
    env_file:
      - ./.env
    depends_on:
      - mongo
    networks:
      - my-network
  node-app-site:
    container_name: express-node-app-container-site
    env_file:
      - ./.env
    depends_on:
      - mongo
    networks:
      - my-network
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    #   - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
      - node-app-site
    networks:
      - my-network
volumes:
  mongo-db:
networks:
  my-network:
    driver: bridge
